name: Upload diagrams

on:
  push:
    branches:
      - master

jobs:
  upload-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install c4builder
        run: npm i -g c4builder

      - name: Generate docs
        run: c4builder

      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          ref: master
          path: ${{ github.repository }}.wiki

      - name: Push to wiki
        env:
          CONTEXT_IMAGE_FILE: './context.svg'
        run: |
          ls -lah
          envsubst < "CUSTOM.md" > "CUSTOM.md"
          git add CUSTOM.md
          git add context.svg
          git diff-index --quiet HEAD || git commit -m "Update diagrams" && git push
        working-directory: ./generated
